version: "3.7"
services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: "db"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=todo
    ports:
      - "5433:5432"
    expose:
      - 5433
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: "redis"


volumes:
  pgdata:


