version: "3.7"
services:
  #  api:
  #    container_name: "api"
  #    command: "uvicorn main:app --reload --host 0.0.0.0"
  #    build:
  #      context: .
  #    ports:
  #      - "8000:8000"
  #    depends_on:
  #      - db
  #    volumes:
  #      - ./:/app

  db:
    image: postgres:latest
    container_name: "db"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=todo
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


